// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_DBSKvWPBjXFZ8-GrtBb2OT_fBsEk6I',
    appId: '1:967747189066:web:cde320201819aba8bea9b3',
    messagingSenderId: '967747189066',
    projectId: 'ethioworks-5e973',
    authDomain: 'ethioworks-5e973.firebaseapp.com',
    storageBucket: 'ethioworks-5e973.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRrbFaI2tLIuGTQOf824IAnKtwiWViN1s',
    appId: '1:967747189066:android:d1b742080c531bedbea9b3',
    messagingSenderId: '967747189066',
    projectId: 'ethioworks-5e973',
    storageBucket: 'ethioworks-5e973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZpM-cEJU4zDUYHRZg40ywzN9wNs4Dk8',
    appId: '1:967747189066:ios:16a6562ad6e7f474bea9b3',
    messagingSenderId: '967747189066',
    projectId: 'ethioworks-5e973',
    storageBucket: 'ethioworks-5e973.firebasestorage.app',
    iosBundleId: 'com.example.ethioworks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZpM-cEJU4zDUYHRZg40ywzN9wNs4Dk8',
    appId: '1:967747189066:ios:16a6562ad6e7f474bea9b3',
    messagingSenderId: '967747189066',
    projectId: 'ethioworks-5e973',
    storageBucket: 'ethioworks-5e973.firebasestorage.app',
    iosBundleId: 'com.example.ethioworks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_DBSKvWPBjXFZ8-GrtBb2OT_fBsEk6I',
    appId: '1:967747189066:web:6f4080d4bba310f4bea9b3',
    messagingSenderId: '967747189066',
    projectId: 'ethioworks-5e973',
    authDomain: 'ethioworks-5e973.firebaseapp.com',
    storageBucket: 'ethioworks-5e973.firebasestorage.app',
  );
}
